#!/bin/bash

export EDITOR=/usr/bin/vim

# MacPorts Installer addition on 2009-01-26_at_10:45:43: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/subversion/bin:/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

export PATH=/bin:/usr/bin:/usr/local/bin:/usr/local/mysqlc/bin:/usr/local/mysql/bin:/usr/local/mysql-5.6.10-osx10.7-x86_64:$PATH

export PATH=/usr/texbin:$PATH
export PATH=/usr/local/go/bin:$PATH
export PATH=~/mybin:~/bin:$PATH
PATH=~/.local/bin:$PATH
PATH=$PATH:/usr/local/scala/bin
PATH=$PATH:$HOME/go/bin
SPARK_HOME=~/dev/spark-2.3.0-bin-hadoop2.7
PATH=$PATH:$SPARK_HOME/bin
PYTHONPATH=$PYTHONPATH:$SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.10.6-src.zip

export PYTHONPATH
export PATH

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi


alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi


# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# ALIASES
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias la='ls -a'
alias ll='ls -lG'
alias ls='ls -G'
alias lr='ls -lrt'
alias g='git'
alias gcu="git commit -m 'update' -a"
alias preview='open -a Preview.app'
alias ipe='open -a Ipe.app'
alias ds='du -s * | sort -g'
alias h='history'
alias docker_bash='docker run -t -i ubuntu /bin/bash'
alias dapn='cd ~/projects/notebooks && ls'
alias dapno='cd ~/projects/notes.hugo && ls'
alias dap='cd ~/projects && ls'
alias dapd='cd ~/dev && ls'
alias pyspark_ipython='PYSPARK_DRIVER_PYTHON=ipython pyspark'
alias python2='~/anaconda3/envs/py27_electrum/bin/python'
alias py27='source activate py27'
alias vi='/usr/bin/vim'
alias bx='bitchx dc_not_dc chat.freenode.net'

# MacPorts Installer addition on 2009-01-26_at_10:45:43: adding an appropriate MANPATH variable for use with MacPorts.
export MANPATH=/opt/local/share/man:$MANPATH

# alias node='/usr/local/bin/node'
# alias npm='/usr/local/bin/npm'

### Added by the Quandl Toolbelt
export PATH="/usr/local/quandl/bin:$PATH"

export PATH="~/anaconda3/envs/363/bin:$PATH"
export CONDA_PREFIX=$HOME/anaconda3/envs/363
export CONDA_DEFAULT_ENV=363

export QUANDL_AUTH='GMs5ZwtAzsTP6MAHoyCH'

export PATH=~/torch/install/bin:$PATH  # Added automatically by torch-dist
export LD_LIBRARY_PATH=~/torch/install/lib:$LD_LIBRARY_PATH  # Added automatically by torch-dist
export DYLD_LIBRARY_PATH=~/torch/install/lib:$DYLD_LIBRARY_PATH  # Added automatically by torch-dist

# alias hub to git
# eval "$(hub alias -s)"

export export LIBFM_PATH=~/dev/libfm/bin

export PARQUET_HOME=~/anaconda
export ARROW_HOME=$HOME/local


# NOTES:
# openssl des3 -in file.txt -out encrypted.txt
# openssl des3 -d -in encrypted.txt -out normal.txt

. $HOME/.bash_profile
# go here if unhappy http://bashrcgenerator.com/
export PS1="\[\033[38;5;14m\]\w\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]\[\033[38;5;11m\]\\$\[$(tput sgr0)\] "

. ~/mybin/functions.sh
