#!/bin/sh
# ip=$(cat ~/syncthing_main/lan_ip_Linux_bleepblop.txt | head -1)
# ssh -t cottrell@$ip tmux -CC $*

while getopts ":m:-:" opt; do
  case ${opt} in
    m)
      machine=$OPTARG
      ;;
    -)
      case "${OPTARG}" in
        machine=*)
          machine=${OPTARG#*=}
          ;;
        *)
          echo "Invalid option: --${OPTARG}" >&2
          exit 1
          ;;
      esac
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
  shift $((OPTIND-1))
done

machine=${machine:-bleepblop}

# 2021 try the ips in some order and use first that works
for ip in $(tac ~/syncthing_main/lan_ip_Linux_"$machine".txt); do
    if $(echo $ip | grep -q ':'); then
        echo skipping $ip
        continue
    elif ssh -o ConnectTimeout=1 -t cottrell@$ip echo yes >/dev/null 2>&1; then
        if [ $(uname) = 'Darwin' ]; then
            cmd="ssh -t cottrell@$ip tmux -CC $*"
            echo $ip is ok trying $cmd
            $cmd
            break  # no need to try others
        else
            xtermcontrol --bg '#300000'
            cmd="ssh cottrell@$ip $*"
            echo $ip is ok trying $cmd
            $cmd
            xtermcontrol --bg '#000000'
            break  # no need to try others
        fi
    else
        echo nope $ip
    fi
done
