#!/bin/bash
dirname=~/Dropbox/misc/nogithub
# vim +'normal Go' +'r!date' $dirname/did.txt
# vim +'normal Go'  +'r!date +\%a\ \%Y-\%m-\%d\ \%H:\%M:\%S\ \%z/\%Z' -- $dirname/did.txt
vim +'normal Go' +'r!date +\%a\ \%d\ \%b\ \%Y\ \%H:\%M:\%S\ \%z; echo -' -- $dirname/did.txt
cd $dirname
git commit -m 'update' -a
