#!/bin/bash

# safer than rm. create date-based folder in trash and move things there.

TRASH=$HOME/.Trash
[[ -e "$TRASH" ]] || mkdir -p $TRASH

until [ "$#" = "0" ];do
    # dest inside loop to avoid collisions on multiple folders
    dest=$TRASH/$(/bin/date +%Y%m%dT%H%M%S.%N)
    [[ -e "$dest" ]] || mkdir -v $dest
    # echo mv -v "$1" "$dest"
    mv -v "$1" "$dest"
    shift
done
