#!/usr/bin/env python3
"""
"""

import glob
import sys
import os
import re

HOME = os.getenv("HOME")
NOTES = os.path.join(HOME, "notes")

padding = "  "
# pattern = re.compile("^[\t\*]*")
def parse_line(line):
   line = line.strip(" ")
   x = line.lstrip("\t*")
   n = len(line) - len(x)
   x = x.strip()
   line = padding * n + x
   # # x = pattern.findall(line)
   # # line = pattern.sub("", line)
   # # s = padding * len(x)
   return(line)

def print_stuff(files):
   # content
   for f in files:
       print("%s:" % f)
       fin = open(f, 'r')
       for x in fin:
           x = x.strip(" \n")
           x = parse_line(x)
           print(x)
       print()
   # index
   print("Index:")
   for f in files:
       print(padding, f)

if __name__ == '__main__':
   script_name = os.path.basename(sys.argv[0])
   if script_name == 'jls':
       files = glob.glob(os.path.join(NOTES, "journal_*"))
   elif script_name == 'nls':
       files = glob.glob(os.path.join(NOTES, "note_*"))
   else:
       print("something is wrong")
       print(script_name)
   files.sort(reverse=False)
   print_stuff(files)
